#!/usr/bin/env python3

import argparse

import anyio

from aioros.master import run


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--port", type=int, default=11311)
    parser.add_argument("-d", "--debug", action="store_true")
    args = parser.parse_args()
    anyio.run(run, args.port, None, args.debug)


if __name__ == "__main__":
    main()
