name: Build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - run: mkdir -p catkin_ws/src
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: catkin_ws/src/aioros
      - run: apt update
      - name: Install dependencies
        run: apt install -y catkin-tools g++ python3-rosdep2 python3-anyio python3-h11 python3-httpx
      - name: Build
        run: |
          cd catkin_ws
          rosdep update
          rosdep install --from-paths src -y --skip-keys "python3-anyio python3-h11 python3-httpx"
          catkin init
          catkin config --install
          catkin build
          . install/setup.sh
          pytest-3 src/aioros/tests
